//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCallAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class org_external
    {
        public int common_id { get; set; }
        public string org_id { get; set; }
        public string org_code { get; set; }
        public string org_name { get; set; }
        public string org_id_parent { get; set; }
    }
}
